// Mocks generated by Mockito 5.4.6 from annotations
// in job_application_tracker/test/features/jobs/job_interviews/interview_list/cubit/interview_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_core/flutter_core.dart' as _i2;
import 'package:job_application/src/domain/entities/job_interview_entity.dart'
    as _i5;
import 'package:job_application/src/domain/repositories/job_interview_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JobInterviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobInterviewRepository extends _i1.Mock
    implements _i3.JobInterviewRepository {
  MockJobInterviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<String>> createInterview(
    _i5.JobInterviewEntity? interview,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createInterview, [interview]),
            returnValue: _i4.Future<_i2.Result<String>>.value(
              _FakeResult_0<String>(
                this,
                Invocation.method(#createInterview, [interview]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<String>>);

  @override
  _i4.Future<_i2.Result<void>> updateInterview(
    _i5.JobInterviewEntity? interview,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInterview, [interview]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#updateInterview, [interview]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> deleteInterview({
    required String? userId,
    required String? jobApplicationId,
    required String? interviewId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInterview, [], {
              #userId: userId,
              #jobApplicationId: jobApplicationId,
              #interviewId: interviewId,
            }),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#deleteInterview, [], {
                  #userId: userId,
                  #jobApplicationId: jobApplicationId,
                  #interviewId: interviewId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.JobInterviewEntity>> watchInterviews({
    required String? userId,
    required String? jobApplicationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchInterviews, [], {
              #userId: userId,
              #jobApplicationId: jobApplicationId,
            }),
            returnValue: _i4.Stream<List<_i5.JobInterviewEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.JobInterviewEntity>>);

  @override
  _i4.Future<_i2.Result<List<_i5.JobInterviewEntity>>> getInterviews({
    required String? userId,
    required String? jobApplicationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInterviews, [], {
              #userId: userId,
              #jobApplicationId: jobApplicationId,
            }),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.JobInterviewEntity>>>.value(
                  _FakeResult_0<List<_i5.JobInterviewEntity>>(
                    this,
                    Invocation.method(#getInterviews, [], {
                      #userId: userId,
                      #jobApplicationId: jobApplicationId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.JobInterviewEntity>>>);

  @override
  _i4.Stream<List<_i5.JobInterviewEntity>> watchUpcomingInterviews({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchUpcomingInterviews, [], {#userId: userId}),
            returnValue: _i4.Stream<List<_i5.JobInterviewEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.JobInterviewEntity>>);
}
