// Mocks generated by Mockito 5.4.6 from annotations
// in location_tracking/test/cubit/location_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_core/flutter_core.dart' as _i2;
import 'package:location_tracking/src/domain/entities/location_entity.dart'
    as _i7;
import 'package:location_tracking/src/domain/entities/location_permission_status.dart'
    as _i8;
import 'package:location_tracking/src/domain/entities/location_result.dart'
    as _i5;
import 'package:location_tracking/src/domain/repositories/location_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.LocationResult> getCurrentLocationWithPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocationWithPermission, []),
            returnValue: _i4.Future<_i5.LocationResult>.value(
              _i6.dummyValue<_i5.LocationResult>(
                this,
                Invocation.method(#getCurrentLocationWithPermission, []),
              ),
            ),
          )
          as _i4.Future<_i5.LocationResult>);

  @override
  _i4.Future<_i2.Result<_i7.LocationEntity>> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i4.Future<_i2.Result<_i7.LocationEntity>>.value(
              _FakeResult_0<_i7.LocationEntity>(
                this,
                Invocation.method(#getCurrentLocation, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i7.LocationEntity>>);

  @override
  _i4.Stream<_i7.LocationEntity> getLocationStream() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationStream, []),
            returnValue: _i4.Stream<_i7.LocationEntity>.empty(),
          )
          as _i4.Stream<_i7.LocationEntity>);

  @override
  _i4.Future<_i2.Result<_i8.LocationPermissionStatus>> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue:
                _i4.Future<_i2.Result<_i8.LocationPermissionStatus>>.value(
                  _FakeResult_0<_i8.LocationPermissionStatus>(
                    this,
                    Invocation.method(#checkPermission, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i8.LocationPermissionStatus>>);

  @override
  _i4.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  double calculateDistance(
    _i7.LocationEntity? start,
    _i7.LocationEntity? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistance, [start, end]),
            returnValue: 0.0,
          )
          as double);
}
