// Mocks generated by Mockito 5.4.6 from annotations
// in location_tracking/test/cubit/places_search_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_core/flutter_core.dart' as _i2;
import 'package:location_tracking/src/domain/entities/place_details_entity.dart'
    as _i6;
import 'package:location_tracking/src/domain/entities/place_prediction_entity.dart'
    as _i5;
import 'package:location_tracking/src/domain/repositories/places_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlacesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesRepository extends _i1.Mock implements _i3.PlacesRepository {
  MockPlacesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.PlacePredictionEntity>>> searchPlaces(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlaces, [query]),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.PlacePredictionEntity>>>.value(
                  _FakeResult_0<List<_i5.PlacePredictionEntity>>(
                    this,
                    Invocation.method(#searchPlaces, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.PlacePredictionEntity>>>);

  @override
  _i4.Future<_i2.Result<_i6.PlaceDetailsEntity>> getPlaceDetails(
    String? placeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaceDetails, [placeId]),
            returnValue: _i4.Future<_i2.Result<_i6.PlaceDetailsEntity>>.value(
              _FakeResult_0<_i6.PlaceDetailsEntity>(
                this,
                Invocation.method(#getPlaceDetails, [placeId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i6.PlaceDetailsEntity>>);
}
