include: package:flutter_lints/flutter.yaml

analyzer:
  # https://github.com/google/json_serializable.dart/issues/885
  # https://github.com/rrousselGit/freezed/issues/488
  # errors:
  # annotate_overrides: ignore

  exclude:
    - "**messages_*.dart"
    - "**l10n.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 80

linter:
  rules:
    # Enforce modular imports
    always_use_package_imports: true
    # Ensure Futures are handled correctly
    avoid_returning_null_for_future: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    # Sort pub dependencies alphabetically
    sort_pub_dependencies: true
