// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf8rsJ0cq9r7hCWolJSd14gzNb1nkmSXQ',
    appId: '1:625002689131:android:38ba11d5f8f0b677b0772e',
    messagingSenderId: '625002689131',
    projectId: 'job-application-tracker-516b1',
    storageBucket: 'job-application-tracker-516b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8H3y-bAsiAXOTy-RDDSYEMt84YnPbf0',
    appId: '1:625002689131:ios:5acd102adef14795b0772e',
    messagingSenderId: '625002689131',
    projectId: 'job-application-tracker-516b1',
    storageBucket: 'job-application-tracker-516b1.firebasestorage.app',
    iosClientId: '625002689131-4qc8o3lj2sh3ko5afp5rsj3jupe4usa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobApplicationTracker',
  );
}
