// Mocks generated by Mockito 5.4.6 from annotations
// in location_tracking/test/repositories/places_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:location_tracking/src/data/datasources/places_remote_data_source.dart'
    as _i3;
import 'package:location_tracking/src/data/models/place_details_model.dart'
    as _i6;
import 'package:location_tracking/src/data/models/place_prediction_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlacesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesRemoteDataSource extends _i1.Mock
    implements _i3.PlacesRemoteDataSource {
  MockPlacesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.PlacesPredictionResponseModel>> searchPlaces({
    required String? query,
    required String? apiKey,
    String? sessionToken,
    String? components = 'country:ph',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlaces, [], {
              #query: query,
              #apiKey: apiKey,
              #sessionToken: sessionToken,
              #components: components,
            }),
            returnValue:
                _i4.Future<
                  _i2.HttpResponse<_i5.PlacesPredictionResponseModel>
                >.value(
                  _FakeHttpResponse_0<_i5.PlacesPredictionResponseModel>(
                    this,
                    Invocation.method(#searchPlaces, [], {
                      #query: query,
                      #apiKey: apiKey,
                      #sessionToken: sessionToken,
                      #components: components,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.PlacesPredictionResponseModel>>);

  @override
  _i4.Future<_i2.HttpResponse<_i6.PlaceDetailsResponseModel>> getPlaceDetails({
    required String? placeId,
    required String? apiKey,
    String? sessionToken,
    String? fields = 'place_id,geometry,formatted_address,name',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaceDetails, [], {
              #placeId: placeId,
              #apiKey: apiKey,
              #sessionToken: sessionToken,
              #fields: fields,
            }),
            returnValue:
                _i4.Future<
                  _i2.HttpResponse<_i6.PlaceDetailsResponseModel>
                >.value(
                  _FakeHttpResponse_0<_i6.PlaceDetailsResponseModel>(
                    this,
                    Invocation.method(#getPlaceDetails, [], {
                      #placeId: placeId,
                      #apiKey: apiKey,
                      #sessionToken: sessionToken,
                      #fields: fields,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i6.PlaceDetailsResponseModel>>);
}
