// Mocks generated by Mockito 5.4.6 from annotations
// in budget_core/test/domain/use_cases/delete_transaction_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:budget_core/src/domain/entities/account_entity.dart' as _i7;
import 'package:budget_core/src/domain/entities/transaction_entity.dart' as _i5;
import 'package:budget_core/src/domain/repositories/account_repository.dart'
    as _i6;
import 'package:budget_core/src/domain/repositories/transaction_repository.dart'
    as _i3;
import 'package:flutter_core/flutter_core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i3.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<void>> save(_i5.TransactionEntity? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#save, [transaction]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#save, [transaction]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [transactionId]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#delete, [transactionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<_i5.TransactionEntity>>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.TransactionEntity>>>.value(
                  _FakeResult_0<List<_i5.TransactionEntity>>(
                    this,
                    Invocation.method(#getAll, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.TransactionEntity>>>);

  @override
  _i4.Future<_i2.Result<_i5.TransactionEntity>> getById(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [transactionId]),
            returnValue: _i4.Future<_i2.Result<_i5.TransactionEntity>>.value(
              _FakeResult_0<_i5.TransactionEntity>(
                this,
                Invocation.method(#getById, [transactionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.TransactionEntity>>);

  @override
  _i4.Future<_i2.Result<List<_i5.TransactionEntity>>> getByAccount(
    String? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByAccount, [accountId]),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.TransactionEntity>>>.value(
                  _FakeResult_0<List<_i5.TransactionEntity>>(
                    this,
                    Invocation.method(#getByAccount, [accountId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.TransactionEntity>>>);

  @override
  _i4.Stream<List<_i5.TransactionEntity>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i4.Stream<List<_i5.TransactionEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.TransactionEntity>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i6.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<void>> save(_i7.AccountEntity? account) =>
      (super.noSuchMethod(
            Invocation.method(#save, [account]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#save, [account])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [accountId]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#delete, [accountId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<_i7.AccountEntity>>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<_i2.Result<List<_i7.AccountEntity>>>.value(
              _FakeResult_0<List<_i7.AccountEntity>>(
                this,
                Invocation.method(#getAll, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<_i7.AccountEntity>>>);

  @override
  _i4.Future<_i2.Result<_i7.AccountEntity>> getById(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [accountId]),
            returnValue: _i4.Future<_i2.Result<_i7.AccountEntity>>.value(
              _FakeResult_0<_i7.AccountEntity>(
                this,
                Invocation.method(#getById, [accountId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i7.AccountEntity>>);

  @override
  _i4.Stream<List<_i7.AccountEntity>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i4.Stream<List<_i7.AccountEntity>>.empty(),
          )
          as _i4.Stream<List<_i7.AccountEntity>>);

  @override
  _i4.Future<_i2.Result<void>> updateBalance(
    String? accountId,
    double? newBalance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalance, [accountId, newBalance]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#updateBalance, [accountId, newBalance]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);
}
